---
title: "Reporte datos sensores ZIM Temporada 2023-2024"
subtitle: "Proyecto FONDEF ID21I10297"
author: "Francisco Zambrano"
date: "`r Sys.time()`"
lang: es
format: html
editor: source
---

## Carga de datos
```{r setup}
#| include: true
#| echo: true
#| warning: false
#| message: false
library(tidyverse)
library(fs)
library(highcharter)
library(gt)


data_sm <- read_rds(dir_ls('../data/procesada/',regexp = 'zim_sm.*rds$'))
data_tur <- read_rds(dir_ls('../data/procesada/',regexp = 'zim_turgor.*rds$'))
```


# Análisis Exploratorio

## Sensores de humedad de suelo

### Box-plot

```{r}
#| warning: false

data_info <- data_sm |> 
  select(sitio,sensor,tratamiento,codigo,unidad) |>
  distinct(sitio,sensor,tratamiento,codigo,unidad)

data_sm |> 
  mutate(unidad = as.factor(unidad)) |> 
  ggplot(aes(unidad,value)) +
  geom_boxplot() +
  facet_grid(sitio~tratamiento) +
  geom_text(data = data_info,aes(unidad,75,label = codigo),size=2) +
  theme_light()
```

### Series de tiempo

```{r}
data_sm |> 
  mutate(unidad = as.factor(unidad)) |> 
  ggplot(aes(hora,value,color=unidad)) +
  geom_point(size=.05) +
  #geom_text(data = data_info,aes(unidad,75,label = codigo),size=2) +
  facet_grid(tratamiento~sitio) +
  theme_bw()

```

## Presión de parche

### Box-plot

```{r}
#| warning: false
data_info <- data_tur |> 
  select(sitio,sensor,tratamiento,codigo,unidad) |>
  distinct(sitio,sensor,tratamiento,codigo,unidad)

data_tur |> 
  mutate(unidad = as.factor(unidad)) |> 
  ggplot(aes(unidad,value)) +
  geom_boxplot() +
  facet_grid(sitio~tratamiento) +
  geom_text(data = data_info,aes(unidad,0,label = codigo),size=2) +
  theme_light()
```

### Series de tiempo

```{r}
data_tur |> 
  drop_na() |> 
  separate(codigo,into = c('codigo','zim'),sep="Z") |> 
  mutate(unidad = as.factor(unidad)) |> 
  group_by(sitio,codigo,zim) |> 
  mutate(value_sc = scale(value)) |> 
  ggplot(aes(hora,value_sc,color=zim)) +
  geom_point(size=.05) +
  #geom_text(data = data_info,aes(unidad,75,label = codigo),size=2) +
  facet_grid(tratamiento+sitio~unidad) +
  theme_bw()
```

## Ciclo diario

```{r}
#| fig.width=5
data_tur |> 
  drop_na() |> 
  mutate(unidad = as.factor(unidad)) |> 
  group_by(sitio,codigo) |> 
  mutate(value_sc = scale(value)) |> 
  drop_na() |> 
  arrange(sitio,tratamiento,unidad) |> 
  mutate(unidad = as.factor(unidad),
         hora_dia = as.numeric(format(hora,"%H"))) |> 
  group_by(sitio,tratamiento,unidad,hora_dia) |> 
  summarize(value_hora = mean(value_sc,na.rm = TRUE)) |> 
  ggplot(aes(hora_dia,value_hora,color=unidad)) +
  geom_point(size=.05) +
  geom_line() +
  #geom_text(data = data_info,aes(unidad,75,label = codigo),size=2) +
  facet_grid(tratamiento+unidad~sitio,scales = 'free_y') +
  theme_bw()
  


```
